source "https://rubygems.org"

gem "jekyll", "~> 3.9.5"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "webrick", "~> 1.8"
gem "ffi", "~> 1.15.5"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "kramdown-parser-gfm"
